# Generated by Django 4.2.13 on 2024-05-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_splitexpense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='splitexpense',
            old_name='user',
            new_name='users',
        ),
    ]
