# Generated by Django 4.2.13 on 2024-05-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_splitexpense_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.ImageField(null=True, upload_to='receipts/'),
        ),
    ]
